DROP DATABASE IF EXISTS spaceX;
CREATE DATABASE spaceX;

USE spaceX;
CREATE TABLE Department(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE Role(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(30) NOT NULL,
    Salary DECIMAL(4) NOT NULL,
    Department_ID INT,
    FOREIGN KEY (Department_ID) REFERENCES Department(id) ON DELETE SET NULL
);

CREATE TABLE Employee(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    First VARCHAR(30) NOT NULL,
    Last VARCHAR(30) NOT NULL,
    Role_ID INT,
  
    FOREIGN KEY (Role_ID) REFERENCES Role(id)  
    -- Manager_ID INT,
    -- FOREIGN KEY (Manager_ID) REFERENCES Manager(id) ON DELETE SET NULL
);

CREATE TABLE Manager(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Employee_ID INT,
    FOREIGN KEY (Employee_ID) REFERENCES Employee(id) ON DELETE SET NULL
);